/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room.gltf 
Author: amurin (https://sketchfab.com/amurin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
*/

import * as THREE from "three";
import * as React from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useEffect, useMemo, useState } from 'react'
import { ScreenContent } from './ScreenContent'
import { ViewKey } from './CameraAnimation'

type GLTFResult = GLTF & {
  nodes: { [key: string]: THREE.Mesh }
  materials: { [key: string]: THREE.Material }
}

interface RoomProps extends React.ComponentProps<'group'> {
  activeView: ViewKey;
  onViewChange: (view: ViewKey) => void;
  isStarted?: boolean;
}

// ─── FAIRY LIGHTS COMPONENT ─────────────────────────────────────────────
function FairyLights({ 
  start, 
  end, 
  sag = 0.4, 
  count = 12, 
  color = "#ffb732",
  intensity = 2.0 
}: { 
  start: [number, number, number], 
  end: [number, number, number], 
  sag?: number, 
  count?: number, 
  color?: string,
  intensity?: number 
}) {
  const bulbs = useMemo(() => {
    const pts = [];
    for (let i = 0; i < count; i++) {
      const t = i / (count - 1);
      const x = start[0] + (end[0] - start[0]) * t;
      const y = start[1] + (end[1] - start[1]) * t - Math.sin(t * Math.PI) * sag;
      const z = start[2] + (end[2] - start[2]) * t;
      pts.push([x, y, z] as [number, number, number]);
    }
    return pts;
  }, [start, end, sag, count]);

  return (
    <group>
      {/* Wire */}
      {bulbs.slice(0, -1).map((pos, i) => {
        const next = bulbs[i + 1];
        const mid = [
          (pos[0] + next[0]) / 2,
          (pos[1] + next[1]) / 2,
          (pos[2] + next[2]) / 2,
        ] as [number, number, number];
        const dx = next[0] - pos[0];
        const dy = next[1] - pos[1];
        const dz = next[2] - pos[2];
        const len = Math.sqrt(dx * dx + dy * dy + dz * dz);
        const angleZ = Math.atan2(dy, dx);
        const angleY = Math.atan2(dz, Math.sqrt(dx * dx + dy * dy));
        
        return (
          <mesh key={`wire-${i}`} position={mid} rotation={[0, -angleY, angleZ]}>
            <cylinderGeometry args={[0.005, 0.005, len, 4]} />
            <meshBasicMaterial color="#111111" />
          </mesh>
        )
      })}

      {/* Bulbs */}
      {bulbs.map((pos, i) => (
        <group key={`bulb-${i}`} position={pos}>
          {/* Inner bright bulb */}
          <mesh>
            <sphereGeometry args={[0.035, 8, 8]} />
            <meshBasicMaterial color="#ffffff" toneMapped={false} />
          </mesh>
          {/* Outer glow halo */}
          <mesh>
            <sphereGeometry args={[0.09, 8, 8]} />
            <meshBasicMaterial color={color} transparent opacity={0.4} toneMapped={false} />
          </mesh>
          
          {(i === 1 || i === Math.floor(count / 2) || i === count - 2) && (
            <pointLight color={color} intensity={intensity * 1.5} distance={7} decay={2} />
          )}
        </group>
      ))}
    </group>
  );
}
// ────────────────────────────────────────────────────────────────────────

export function Model({ activeView, onViewChange, isStarted = false, ...props }: RoomProps) {
  const { nodes, materials } = useGLTF('/assets/models/room.gltf') as unknown as GLTFResult
  const [hovered, setHovered] = useState(false);
  const [showButton, setShowButton] = useState(false);

  useEffect(() => {
    if (activeView === "computer") {
      setShowButton(false);
    } else if (isStarted) {
      // Delay showing the button by 2 seconds when returning from computer view
      // OR immediately if we just finished the initial loading screen
      const timer = setTimeout(() => {
        setShowButton(true);
      }, 2000);
      return () => clearTimeout(timer);
    }
  }, [activeView, isStarted]);
   
  useEffect(() => {
    // 1. MONITOR & PC LIGHTS
    const screenMat = materials.screen as THREE.MeshStandardMaterial;
    screenMat.emissive = new THREE.Color("#00eeff");
    screenMat.emissiveIntensity = 20; // Increased from 16

    const lightMat = materials.light as THREE.MeshStandardMaterial;
    lightMat.emissive = new THREE.Color("#a855f7"); 
    lightMat.emissiveIntensity = 12; // Increased from 10

    // 2. WALLS
    const wallMat = materials.pared as THREE.MeshStandardMaterial;
    wallMat.color.set("#252836");
    wallMat.roughness = 0.85;
    wallMat.metalness = 0.1;

    // 3. FLOOR
    const floorMat = materials.suelo as THREE.MeshStandardMaterial;
    floorMat.color.set("#15161c");
    floorMat.roughness = 0.6;
    floorMat.metalness = 0.2;

    // 4. DOOR
    const doorMat = materials.puerta as THREE.MeshStandardMaterial;
    doorMat.color.set("#363a4d");
    doorMat.roughness = 0.7;

    // 5. BED SHEETS
    const sheetsMat = materials.sabanas as THREE.MeshStandardMaterial;
    sheetsMat.color.set("#384259");
    sheetsMat.roughness = 0.9;

    // 6. FURNITURE
    const bedFrame = materials.base_cama as THREE.MeshStandardMaterial;
    bedFrame.color.set("#1c1c24");

    const mattress = materials.colchon as THREE.MeshStandardMaterial;
    mattress.color.set("#1e2029");
    
    const blackItems = materials.negro as THREE.MeshStandardMaterial;
    blackItems.color.set("#14151c");
    blackItems.roughness = 0.6;

    const chair = materials.silla2 as THREE.MeshStandardMaterial;
    chair.color.set("#232533");

    // 7. DESK LAMP
    const lampMat = materials.lamapra as THREE.MeshStandardMaterial;
    lampMat.color.set("#ffe6b3");
    lampMat.emissive = new THREE.Color("#ffb732");
    lampMat.emissiveIntensity = 3.0;

    // 8. EXTERIOR WALLS (Pure black to hide the outside shell)
    const outsideMat = materials.afuera as THREE.MeshStandardMaterial;
    outsideMat.color.set("#000000");
    outsideMat.emissive = new THREE.Color("#000000"); 
    outsideMat.emissiveIntensity = 0;

    Object.values(materials).forEach(mat => {
      mat.needsUpdate = true;
    });

  }, [materials]);

  return (
    <group {...props} dispose={null}>
      
      {/* ─── LEFT WALL FAIRY LIGHTS ──────────────────────────────────── */}
      <FairyLights start={[-4.5, 3.9, -3.5]} end={[-4.5, 3.6, -0.5]} sag={0.35} count={12} color="#ffb732" intensity={20.5} />
      <FairyLights start={[-4.5, 3.6, -0.5]} end={[-4.5, 3.9, 1.5]} sag={0.25} count={10} color="#ffb732" intensity={2.5} />
      {/* ───────────────────────────────────────────────────────────── */}


      {/* ─── PURE MOONLIGHT WINDOW ILLUMINATION ──────────────────────── */}
      
      {/* 1. Backdrop plane placed OUTSIDE the window to block the pure black background. 
             This makes the window hole look like a glowing midnight sky. */}
      <mesh position={[1.5, 3.0, -4.8]}>
        <planeGeometry args={[4.5, 3.5]} />
        <meshBasicMaterial color="#1e3b5e" toneMapped={false} />
      </mesh>

      {/* 2. Primary moonlight shining FROM the window INTO the room */}
      <pointLight position={[1.5, 3.0, -4.0]} intensity={25.0} color="#88bbff" distance={10} decay={2} />
      
      {/* 3. Moonlight reflecting off the floor/bed */}
      <pointLight position={[1.5, 1.0, -2.0]} intensity={8.0} color="#a3c2ff" distance={6} decay={2} />
      
      {/* ───────────────────────────────────────────────────────────── */}


      <group position={[0.095, -0.373, 0.14]} scale={4.819}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.pared} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.suelo} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.afuera} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.puerta} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.negro} />
      </group>
      <group position={[-1.049, -0.692, 1.149]} scale={1.419}>
        <mesh geometry={nodes.Object_16.geometry} material={materials.base_cama} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.colchon} />
      </group>
      <group position={[-3.882, 1.509, -2.596]} scale={0.12}>
        <mesh geometry={nodes.Object_25.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Material.002']} />
      </group>
      <group position={[-3.958, 1.431, -3.489]} scale={0.077}>
        <mesh geometry={nodes.Object_30.geometry} material={materials.negro} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.pcinsidenormal} />
      </group>
      
      {/* PC Monitor Group */}
      <group position={[-3.781, 2.47, -1.132]} scale={1.456}>
        <mesh geometry={nodes.Object_33.geometry} material={materials.negro} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.screen} />
        <mesh geometry={nodes.Object_34.geometry}>
          <ScreenContent geometry={nodes.Object_34.geometry} activeView={activeView as "about" | "portfolio" | undefined} />
        </mesh>
        
        {/* 3D Interactive Button - Stays fixed to the monitor */}
        {showButton && (
          <Html
            position={[0.3, 0.4, 0.5]} // Position relative to monitor group
            center
            distanceFactor={8}
            occlude={false}
            style={{
              transition: 'all 0.5s',
              opacity: hovered ? 1 : 0.8,
              transform: `scale(${hovered ? 1.2 : 1})`,
            }}
          >
            <div 
              style={{ 
                position: 'relative', 
                cursor: 'pointer',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                gap: '8px'
              }}
              onMouseEnter={() => setHovered(true)}
              onMouseLeave={() => setHovered(false)}
              onClick={() => onViewChange("computer")}
            >
              {/* Pulsing Dot */}
              <div style={{ position: 'relative' }}>
                <div style={{
                  width: '12px',
                  height: '12px',
                  background: 'white',
                  borderRadius: '50%',
                  boxShadow: '0 0 15px white',
                }} />
                <div style={{
                  position: 'absolute',
                  top: '-4px',
                  left: '-4px',
                  width: '20px',
                  height: '20px',
                  border: '2px solid white',
                  borderRadius: '50%',
                  animation: 'pulse 2s infinite',
                }} />
              </div>
              
              {/* Small Label */}
              <span style={{
                color: 'white',
                fontSize: '10px',
                textTransform: 'uppercase',
                letterSpacing: '0.1em',
                background: 'rgba(0,0,0,0.5)',
                padding: '2px 8px',
                borderRadius: '10px',
                whiteSpace: 'nowrap',
                pointerEvents: 'none',
                opacity: hovered ? 1 : 0.7
              }}>
                View Computer
              </span>

              <style>{`
                @keyframes pulse {
                  0% { transform: scale(1); opacity: 1; }
                  100% { transform: scale(2); opacity: 0; }
                }
              `}</style>
            </div>
          </Html>
        )}

        <pointLight position={[0.6, 0, 0]} intensity={8.5} color="#00eeff" distance={5.0} decay={2} />
      </group>

      <group position={[-2.793, 1.422, -2.237]} scale={[0.137, 0.04, 0.083]}>
        <mesh geometry={nodes.Object_36.geometry} material={materials.negro} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.light} />
      </group>
      <group position={[-2.859, 1.4, -1.158]} scale={[0.266, 0.019, 0.797]}>
        <mesh geometry={nodes.Object_41.geometry} material={materials.negro} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.material} />
      </group>
      <group position={[0.261, 0.659, -2.511]} rotation={[-Math.PI, 0, 0]} scale={[-0.296, 0.034, 0.034]}>
        <mesh geometry={nodes.Object_46.geometry} material={materials.base_cama} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.gris} />
      </group>
      
      {/* Desk Lamp */}
      <group position={[0.245, 1.026, -3.312]} scale={[0.316, 0.045, 0.316]}>
        <mesh geometry={nodes.Object_49.geometry} material={materials.lamapra} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.negro} />
        <pointLight position={[0, 4, 0]} intensity={5.5} color="#ffb732" distance={4} decay={2} />
      </group>

      <group position={[-2.771, 4.559, -3.744]} rotation={[Math.PI, 0, 2.849]} scale={[0.085, 0.433, 0.303]}>
        <mesh geometry={nodes.Object_54.geometry} material={materials.pages} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.libro} />
      </group>

      <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} position={[-3.66, 0.011, 1.339]} scale={0.577} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_0} position={[-3.492, 0.078, 1.435]} rotation={[0, 0, -0.878]} scale={0.577} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.negro} position={[-3.58, 0.515, 1.407]} scale={0.394} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.sabanas} position={[3.11, 0.988, -3.333]} rotation={[0.604, 0, 0]} scale={[1.205, 1.596, 1.205]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.sabanas} position={[3.211, 1.29, -0.072]} scale={[2.502, 1.205, 3.534]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.negro} position={[-2.845, 1.371, -1.386]} scale={1.205} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.base_cama} position={[-2.943, 1.349, -2.506]} scale={[1.205, 0.12, 1.205]} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.silla2} position={[-2.496, -0.292, -0.907]} rotation={[-0.498, -1.215, 1.1]} scale={0.083} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.gris} position={[-4.157, 2.42, 4.442]} rotation={[0, 0, -Math.PI / 2]} scale={0.111} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.base_cama} position={[-2.92, 4.041, -3.764]} scale={[1.205, 0.086, 0.455]} />

    </group>
  )
}

useGLTF.preload('/assets/models/room.gltf')